version: "3.8"
services:
  flaskapp:
    build: .
    ports:
      - "80:80"
      - "443:443"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./captures:/captures
      - ./certs:/certs
    network_mode: "host"
