version: "3.8"
services:
  flaskapp:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./captures:/captures
      - ./certs:/certs
    network_mode: "host"
